# Generated by Django 3.1.2 on 2020-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201013_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='cta_link',
            field=models.SlugField(max_length=1024),
        ),
    ]
