# Generated by Django 3.1.2 on 2020-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201013_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='cta_link',
            field=models.CharField(max_length=500),
        ),
    ]
