# Generated by Django 3.1.2 on 2020-11-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201013_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, default='/media/slides/generic.jpg', null=True, upload_to='slides'),
        ),
    ]
