# Generated by Django 3.1.2 on 2020-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201121_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, default='/slides/generic.jpg', null=True, upload_to='slides'),
        ),
    ]
