# Generated by Django 3.1.2 on 2020-10-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='products.style'),
        ),
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
