# Generated by Django 3.1.2 on 2020-10-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201014_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='highlight',
            field=models.BooleanField(default=True),
        ),
    ]
