# Generated by Django 3.1.2 on 2020-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producer_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producers'),
        ),
    ]
