# Generated by Django 3.1.2 on 2020-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201017_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_order',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
