# Generated by Django 3.1.2 on 2020-10-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_units_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='products.style'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_order',
            field=models.IntegerField(default=24),
        ),
    ]
