# Generated by Django 3.1.2 on 2020-10-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
        ('products', '0007_auto_20201017_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producers.producer'),
        ),
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
