# Generated by Django 3.1.2 on 2020-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201019_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(choices=[('bottle', 'bottle'), ('can', 'can'), ('keg', 'keg')], default='bottle', max_length=10),
        ),
    ]
