# Generated by Django 3.1.2 on 2020-11-22 11:31

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201119_1651'),
    ]

    operations = [
        UnaccentExtension()
    ]
